# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘InstaGramLogin’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 
 use_frameworks!

    pod 'Crashlytics'
    pod 'Fabric'
    pod 'Alamofire’, '~> 4.0'
    pod 'Whisper', '~> 4.0'
    pod 'ReachabilitySwift', '~> 3'
    pod 'Kingfisher', '~> 3.2'
end
